### ISSUE TITLE
error parsing module version    Malformed version: (devel)

### ISSUE THREAD

**Issue by Will-Will-Will-Wu** [open-telemetry/opentelemetry-go-instrumentation#1224] opened 2024-10-29 02:52 UTC
os: ghcr.io/open-telemetry/opentelemetry-go-instrumentation/autoinstrumentation-go:v0.14.0-alpha 

logs:

```terminal
{"level":"info","ts":1730170088.0390139,"logger":"go.opentelemetry.io/auto","caller":"cli/main.go:86","msg":"building OpenTelemetry Go instrumentation ...","globalImpl":false}
{"level":"info","ts":1730170090.039836,"logger":"Instrumentation.Analyzer","caller":"process/discover.go:67","msg":"found process","pid":7}
{"level":"error","ts":1730170090.040527,"logger":"Instrumentation.Analyzer","caller":"process/analyze.go:83","msg":"error parsing module version","error":"Malformed version: (devel)","stacktrace":"go.opentelemetry.io/auto/internal/pkg/process.(*Analyzer).Analyze\n\t/app/internal/pkg/process/analyze.go:83\ngo.opentelemetry.io/auto.NewInstrumentation\n\t/app/instrumentation.go:133\nmain.main\n\t/app/cli/main.go:104\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:271"}
{"level":"info","ts":1730170091.4496355,"logger":"Instrumentation.Allocate","caller":"process/allocate.go:73","msg":"Detaching from process","pid":7}
{"level":"info","ts":1730170091.4498608,"logger":"Instrumentation","caller":"app/instrumentation.go:144","msg":"target process analysis completed","pid":7,"go_version":"1.20.3","dependencies":{"ariga.io/atlas":"0.10.2-0.20230427182402-87a07dfb83bf","entgo.io/ent":"0.12.3","github.com/agext/levenshtein":"1.2.1","github.com/apparentlymart/go-textseg/v13":"13.0.0","github.com/beorn7/perks":"1.0.1","github.com/bluele/gcache":"0.0.2","github.com/bwmarrin/snowflake":"0.3.0","github.com/cenkalti/backoff/v4":"4.2.1","github.com/cespare/xxhash/v2":"2.2.0","github.com/coreos/go-semver":"0.3.1","github.com/coreos/go-systemd/v22":"22.5.0","github.com/davecgh/go-spew":"1.1.2-0.20180830191138-d8f796af33cc","github.com/dgryski/go-rendezvous":"0.0.0-20200823014737-9f7001d12a5f","github.com/emicklei/go-restful/v3":"3.9.0","github.com/fatih/color":"1.15.0","github.com/fsnotify/fsnotify":"1.7.0","github.com/go-logr/logr":"1.2.4","github.com/go-logr/stdr":"1.2.2","github.com/go-openapi/inflect":"0.19.0","github.com/go-openapi/jsonpointer":"0.19.6","github.com/go-openapi/jsonreference":"0.20.1","github.com/go-openapi/swag":"0.22.3","github.com/go-redis/redis/v8":"8.11.5","github.com/go-sql-driver/mysql":"1.7.1","github.com/gogf/gf/v2":"2.7.0","github.com/gogo/protobuf":"1.3.2","github.com/golang-jwt/jwt/v4":"4.5.0","github.com/golang/mock":"1.6.0","github.com/golang/protobuf":"1.5.3","github.com/google/gnostic":"0.5.7-v3refs","github.com/google/go-cmp":"0.5.9","github.com/google/gofuzz":"1.2.0","github.com/google/uuid":"1.3.1","github.com/grpc-ecosystem/grpc-gateway/v2":"2.15.0","github.com/hashicorp/errwrap":"1.1.0","github.com/hashicorp/go-multierror":"1.1.1","github.com/hashicorp/hcl/v2":"2.13.0","github.com/jinzhu/copier":"0.4.0","github.com/jinzhu/inflection":"1.0.0","github.com/jinzhu/now":"1.1.5","github.com/josharian/intern":"1.0.0","github.com/json-iterator/go":"1.1.12","github.com/karlseguin/ccache/v3":"3.0.3","github.com/longbridgeapp/sqlparser":"0.3.1","github.com/mailru/easyjson":"0.7.7","github.com/mattn/go-colorable":"0.1.13","github.com/mattn/go-isatty":"0.0.17","github.com/matttproud/golang_protobuf_extensions":"1.0.4","github.com/mitchellh/go-wordwrap":"0.0.0-20150314170334-ad45545899c7","github.com/modern-go/concurrent":"0.0.0-20180306012644-bacd9c7ef1dd","github.com/modern-go/reflect2":"1.0.2","github.com/munnerz/goautoneg":"0.0.0-20191010083416-a7dc8b61c822","github.com/openzipkin/zipkin-go":"0.4.1","github.com/pelletier/go-toml/v2":"2.1.0","github.com/philchia/agollo/v4":"4.1.5","github.com/pkg/errors":"0.9.1","github.com/prometheus/client_golang":"1.16.0","github.com/prometheus/client_model":"0.3.0","github.com/prometheus/common":"0.42.0","github.com/prometheus/procfs":"0.10.1","github.com/redis/go-redis/v9":"9.5.1","github.com/shopspring/decimal":"1.3.1","github.com/spaolacci/murmur3":"1.1.0","github.com/spf13/cast":"1.6.0","github.com/zclconf/go-cty":"1.8.0","github.com/zeromicro/go-zero":"1.6.2","gitlab.1319labels.com/zero-core/common":"1.0.20","gitlab.1319labels.com/zero-core/sharding":"1.0.1","gitlab.1319labels.com/zero-core/zorm-cache":"1.0.1","go.etcd.io/etcd/api/v3":"3.5.9","go.etcd.io/etcd/client/pkg/v3":"3.5.9","go.etcd.io/etcd/client/v3":"3.5.9","go.opentelemetry.io/otel":"1.16.0","go.opentelemetry.io/otel/exporters/jaeger":"1.16.0","go.opentelemetry.io/otel/exporters/otlp/internal/retry":"1.16.0","go.opentelemetry.io/otel/exporters/otlp/otlptrace":"1.16.0","go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc":"1.16.0","go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp":"1.16.0","go.opentelemetry.io/otel/exporters/stdout/stdouttrace":"1.16.0","go.opentelemetry.io/otel/exporters/zipkin":"1.16.0","go.opentelemetry.io/otel/metric":"1.16.0","go.opentelemetry.io/otel/sdk":"1.16.0","go.opentelemetry.io/otel/trace":"1.16.0","go.opentelemetry.io/proto/otlp":"0.19.0","go.uber.org/atomic":"1.10.0","go.uber.org/automaxprocs":"1.5.2","go.uber.org/multierr":"1.9.0","go.uber.org/zap":"1.24.0","golang.org/x/crypto":"0.19.0","golang.org/x/exp":"0.0.0-20230817173708-d852ddb80c63","golang.org/x/mod":"0.12.0","golang.org/x/net":"0.17.0","golang.org/x/oauth2":"0.7.0","golang.org/x/sys":"0.17.0","golang.org/x/term":"0.17.0","golang.org/x/text":"0.14.0","golang.org/x/time":"0.3.0","golang.org/x/tools":"0.12.1-0.20230815132531-74c255bcf846","google.golang.org/genproto":"0.0.0-20230526161137-0005af68ea54","google.golang.org/genproto/googleapis/api":"0.0.0-20230525234035-dd9d682886f9","google.golang.org/genproto/googleapis/rpc":"0.0.0-20230525234030-28d5490b6b19","google.golang.org/grpc":"1.57.0","google.golang.org/protobuf":"1.32.0","gopkg.in/inf.v0":"0.9.1","gopkg.in/yaml.v2":"2.4.0","gopkg.in/yaml.v3":"3.0.1","gorm.io/datatypes":"1.1.1-0.20230130040222-c43177d3cf8c","gorm.io/driver/mysql":"1.5.1","gorm.io/gen":"0.3.23","gorm.io/gorm":"1.25.10","gorm.io/hints":"1.1.2","gorm.io/plugin/dbresolver":"1.4.2","gorm.io/plugin/prometheus":"0.0.0-20230504115745-1aec2356381b","k8s.io/api":"0.26.3","k8s.io/apimachinery":"0.28.0-alpha.1","k8s.io/client-go":"0.26.3","k8s.io/klog/v2":"2.100.1","k8s.io/kube-openapi":"0.0.0-20230524182850-78281498afbb","k8s.io/utils":"0.0.0-20230406110748-d93618cff8a2","sigs.k8s.io/json":"0.0.0-20221116044647-bc3834ca7abd","sigs.k8s.io/structured-merge-diff/v4":"4.2.3","sigs.k8s.io/yaml":"1.3.0","std":"1.20.3"},"total_functions_found":10}
{"level":"info","ts":1730170091.450531,"logger":"go.opentelemetry.io/auto","caller":"cli/main.go:119","msg":"starting instrumentation..."}
{"level":"info","ts":1730170091.5778637,"logger":"Instrumentation.Manager","caller":"instrumentation/manager.go:197","msg":"loading probe","name":"google.golang.org/grpc/client"}
{"level":"info","ts":1730170093.3671894,"logger":"Instrumentation.Manager","caller":"instrumentation/manager.go:197","msg":"loading probe","name":"google.golang.org/grpc/server"}
{"level":"info","ts":1730170093.5680568,"logger":"Instrumentation.Manager","caller":"instrumentation/manager.go:197","msg":"loading probe","name":"net/http/server"}
{"level":"info","ts":1730170093.9655976,"logger":"Instrumentation.Manager","caller":"instrumentation/manager.go:197","msg":"loading probe","name":"net/http/client"}
{"level":"info","ts":1730170094.0637686,"logger":"Instrumentation.Manager","caller":"instrumentation/manager.go:197","msg":"loading probe","name":"database/sql/client"}
{"level":"info","ts":1730170094.2862542,"logger":"go.opentelemetry.io/auto","caller":"cli/main.go:115","msg":"instrumentation loaded successfully"}
```

**Comment by MrAlias** [comment] 2024-10-29 20:12
Thank you for reporting this bug. It looks to be a duplicate of #1049. I am going to close this so we can consolidate the thread there.

Please do the following:

1. Re-run your application that caused this error with the most recent release of auto-instrumentation. Your logs are missing critical information added in that release
2. Include in a comment on #1049 information about your failure:
  - The version of auto-instrumentation used
  - The `go.mod` of the target process you are instrumenting
  - The updated log message from the latest version of auto-instrumentation

**Closed by MrAlias** 2024-10-29 20:12 UTC
Labels: bug

**Comment by Will-Will-Will-Wu** [comment] 2024-10-30 01:09
╮(╯▽╰)╭
