### ISSUE TITLE
Trace and span IDs not being updated

### ISSUE THREAD

**Issue by rogercoll** [open-telemetry/opentelemetry-go-instrumentation#28] opened 2023-02-13 16:46 UTC
### Describe the bug

Trace and span IDS are always set to 0.

### Environment

 - OS: Ubuntu 22.04 amd64
 - Go Version: 1.19.5

### To Reproduce

1. Use https://github.com/keyval-dev/launcher to execute the latest version (v0.71.0) of the OpenTelemetry Collector Contrib 
2. Launch the instrumentation tool with the following command:
OTEL_TARGET_EXE=/usr/bin/otelcol-contrib OTEL_EXPORTER_OTLP_ENDPOINT=0.0.0.0:4317 OTEL_SERVICE_NAME=collector ./otel-go-instrumentation

3. See error:

```
{"level":"info","ts":1676306465.655687,"caller":"grpc/probe.go:214","msg":"got spancontext","trace_id":"00000000000000000000000000000000","span_id":"0000000000000000"}
{"level":"info","ts":1676306465.6558187,"caller":"opentelemetry/controller.go:59","msg":"got event","attrs":[{"Key":"rpc.system","Value":{"Type":"STRING","Value":"grpc"}},{"Key":"rpc.service","Value":{"Type":"STRING","Value":""}},{"Key":"net.peer.ip","Value":{"Type":"STRING","Value":""}},{"Key":"net.peer.name","Value":{"Type":"STRING","Value":""}}]}
{"level":"info","ts":1676306467.4758658,"caller":"grpc/probe.go:214","msg":"got spancontext","trace_id":"00000000000000000000000000000000","span_id":"0000000000000000"}
{"level":"info","ts":1676306467.4759538,"caller":"opentelemetry/controller.go:59","msg":"got event","attrs":[{"Key":"rpc.system","Value":{"Type":"STRING","Value":"grpc"}},{"Key":"rpc.service","Value":{"Type":"STRING","Value":""}},{"Key":"net.peer.ip","Value":{"Type":"STRING","Value":""}},{"Key":"net.peer.name","Value":{"Type":"STRING","Value":""}}]}
{"level":"info","ts":1676306470.6999974,"caller":"grpc/probe.go:214","msg":"got spancontext","trace_id":"00000000000000000000000000000000","span_id":"0000000000000000"}
{"level":"info","ts":1676306470.7000897,"caller":"opentelemetry/controller.go:59","msg":"got event","attrs":[{"Key":"rpc.system","Value":{"Type":"STRING","Value":"grpc"}},{"Key":"rpc.service","Value":{"Type":"STRING","Value":""}},{"Key":"net.peer.ip","Value":{"Type":"STRING","Value":""}},{"Key":"net.peer.name","Value":{"Type":"STRING","Value":""}}]}
{"level":"info","ts":1676306472.459095,"caller":"grpc/probe.go:214","msg":"got spancontext","trace_id":"00000000000000000000000000000000","span_id":"0000000000000000"}

```

### Expected behavior

`trace_id` and `span_id` are always set to 0000000000000000

**Comment by rogercoll** [comment] 2023-02-14 08:31
Using the http server example shown in https://github.com/open-telemetry/opentelemetry-go-instrumentation/issues/17, the issue is similar, no trace or span id is reported in the traces.

**Comment by pdelewski** [comment] 2023-04-03 16:29
@rogercoll I tried to reproduce (infortunately on different ubuntu and Go version) this issue with example from #17 and would like to clarify, when you say "no trace or span id is reported in the traces" you mean `collector` side or `otel-go-instrumentation` log as above (the thing is I'm not getting this kind of message from `otel-go-instrumentation` process).

**Comment by damemi** [comment] 2023-04-03 16:44
@rogercoll are you setting the `OTEL_PROPAGATORS` environment variable? I hit the same issue until I set that eg https://github.com/open-telemetry/opentelemetry-go-instrumentation/pull/46/files#diff-d809bd2e3528bad1b6ef0815ea0ee2d5ed9de5df6ed0acae88823157825a026aR53-R54

@pdelewski your error looks like the offsets may be missing for your Go version, have you tried running `make offsets` and re-building the agent? I updated the latest offsets in #46 as well so that should be merged soon

**Comment by pdelewski** [comment] 2023-04-03 16:52
@pdelewski I looked into offsets and it seems its there, however let me double check that

**Comment by MikeGoldsmith** [comment] 2023-05-03 09:59
I think this may be resolved following a number of fixes including no longer using the keyval launcher, updating offsets, streamlining probes, updating eBPF maps, etc.

@rogercoll Please can you try again and report back?

**Closed** 2023-05-12 17:27 UTC
Labels: bug
