### ISSUE TITLE
opentelemetry-go-instrumentation crashes when an HTTP call is made

### ISSUE THREAD

**Issue by matheusjunior** [open-telemetry/opentelemetry-go-instrumentation#560] opened 2023-12-16 18:44 UTC
### Describe the bug

`opentelemetry-go-instrumentation` binary crashes if there is an external HTTP call, e.g., `http.Get`, in the program to be instrumented.

### Environment

 - OS: Linux matheus 6.2.0-37-generic 22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov  2 18:01:13 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
 - Go Version: go version go1.21.4 linux/amd64
 - Version: v0.9.0-alpha

### To Reproduce

1. Build the sample program (listed below): `go build main.go`
2. Run the binary: `./main`
3. Run `opentelemetry-go-instrumentation` binary: `sudo OTEL_GO_AUTO_TARGET_EXE=<path_to_target_exe>  OTEL_SERVICE_NAME=webserver OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4318 ./otel-go-instrumentation`
4. See error:
```bash
{"level":"info","ts":1702752036.6518192,"logger":"go.opentelemetry.io/auto","caller":"cli/main.go:94","msg":"building OpenTelemetry Go instrumentation ...","globalImpl":false}
{"level":"info","ts":1702752038.660148,"logger":"Instrumentation.Analyzer","caller":"process/discover.go:69","msg":"found process","pid":525455}
{"level":"info","ts":1702752038.66466,"logger":"Instrumentation.Analyzer","caller":"process/analyze.go:98","msg":"found function","function_name":{"Name":"net/http.serverHandler.ServeHTTP","Offset":2248416,"ReturnOffsets":[2248563]}}
{"level":"info","ts":1702752038.6646898,"logger":"Instrumentation.Analyzer","caller":"process/analyze.go:98","msg":"found function","function_name":{"Name":"net/http.(*Transport).roundTrip","Offset":2290336,"ReturnOffsets":[2290805,2290881,2291354,2291579,2291665,2291833,2291844,2292576,2292741,2292814,2292902,2292973,2293033,2293453,2293655]}}
{"level":"info","ts":1702752038.664886,"logger":"Instrumentation.Allocate.TracedProgram","caller":"ptrace/ptrace_linux.go:133","msg":"attach successfully","tid":525455}
{"level":"info","ts":1702752038.6649966,"logger":"Instrumentation.Allocate.TracedProgram","caller":"ptrace/ptrace_linux.go:133","msg":"attach successfully","tid":525456}
{"level":"info","ts":1702752038.6650558,"logger":"Instrumentation.Allocate.TracedProgram","caller":"ptrace/ptrace_linux.go:133","msg":"attach successfully","tid":525457}
{"level":"info","ts":1702752038.6651816,"logger":"Instrumentation.Allocate.TracedProgram","caller":"ptrace/ptrace_linux.go:133","msg":"attach successfully","tid":525458}
{"level":"info","ts":1702752038.665196,"logger":"Instrumentation.Allocate.TracedProgram","caller":"ptrace/ptrace_linux.go:133","msg":"attach successfully","tid":525459}
{"level":"info","ts":1702752038.6652057,"logger":"Instrumentation.Allocate.TracedProgram","caller":"ptrace/ptrace_linux.go:133","msg":"attach successfully","tid":525460}
{"level":"info","ts":1702752038.665266,"logger":"Instrumentation.Allocate.TracedProgram","caller":"ptrace/ptrace_linux.go:133","msg":"attach successfully","tid":525464}
{"level":"info","ts":1702752038.6652775,"logger":"Instrumentation.Allocate.TracedProgram","caller":"ptrace/ptrace_linux.go:133","msg":"attach successfully","tid":525465}
{"level":"info","ts":1702752038.6653988,"logger":"Instrumentation.Allocate.TracedProgram","caller":"ptrace/ptrace_linux.go:133","msg":"attach successfully","tid":525466}
{"level":"info","ts":1702752038.6655502,"logger":"Instrumentation.Allocate.TracedProgram","caller":"ptrace/ptrace_linux.go:234","msg":"Detected linux kernel version","version":"6.2.0"}
{"level":"info","ts":1702752038.665642,"logger":"Instrumentation.Allocate.TracedProgram","caller":"ptrace/ptrace_linux.go:246","msg":"mlock ret","ret":0}
{"level":"info","ts":1702752038.6656485,"logger":"Instrumentation.Allocate","caller":"process/allocate.go:64","msg":"Detaching from process","pid":525455}
{"level":"info","ts":1702752038.6656613,"logger":"Instrumentation.Allocate","caller":"process/allocate.go:43","msg":"mmaped remote memory","start_addr":"7F6EC2F7E000","end_addr":"7F6EC2FFE000"}
{"level":"info","ts":1702752038.665668,"logger":"Instrumentation","caller":"opentelemetry-go-instrumentation/instrumentation.go:134","msg":"target process analysis completed","pid":525455,"go_version":"1.21.4","dependencies":{"-buildmode=exe":null,"-compiler=gc":null,"CGO_CFLAGS=":null,"CGO_CPPFLAGS=":null,"CGO_CXXFLAGS=":null,"CGO_ENABLED=1":null,"CGO_LDFLAGS=":null,"DefaultGODEBUG=panicnil=1":null,"GOAMD64=v1":null,"GOARCH=amd64":null,"GOOS=linux":null,"command-line-arguments":null,"std":"1.21.4"},"total_functions_found":2}
{"level":"info","ts":1702752038.665695,"logger":"Instrumentation.Manager","caller":"instrumentation/manager.go:107","msg":"no functions found for probe, removing","name":"github.com/gin-gonic/gin"}
{"level":"info","ts":1702752038.665703,"logger":"Instrumentation.Manager","caller":"instrumentation/manager.go:107","msg":"no functions found for probe, removing","name":"database/sql"}
{"level":"info","ts":1702752038.665709,"logger":"Instrumentation.Manager","caller":"instrumentation/manager.go:107","msg":"no functions found for probe, removing","name":"google.golang.org/grpc/client"}
{"level":"info","ts":1702752038.665715,"logger":"Instrumentation.Manager","caller":"instrumentation/manager.go:107","msg":"no functions found for probe, removing","name":"google.golang.org/grpc/server"}
{"level":"info","ts":1702752038.665723,"logger":"go.opentelemetry.io/auto","caller":"cli/main.go:107","msg":"starting instrumentation..."}
{"level":"info","ts":1702752038.6657908,"logger":"Instrumentation.Manager","caller":"instrumentation/manager.go:177","msg":"Mounting bpffs","allocations_details":{"StartAddr":140113694154752,"EndAddr":140113694679040}}
{"level":"info","ts":1702752038.665834,"logger":"Instrumentation.Manager","caller":"instrumentation/manager.go:162","msg":"loading probe","name":"net/http/server"}
{"level":"info","ts":1702752038.7444117,"logger":"Instrumentation.Manager","caller":"instrumentation/manager.go:162","msg":"loading probe","name":"net/http/client"}
{"level":"error","ts":1702752038.7531135,"logger":"Instrumentation.Manager","caller":"instrumentation/manager.go:165","msg":"error while loading probes, cleaning up","name":"net/http/client","error":"field UprobeTransportRoundTrip: program uprobe_Transport_roundTrip: load program: invalid argument: unknown func bpf_probe_write_user#36 (617 line(s) omitted)","stacktrace":"go.opentelemetry.io/auto/internal/pkg/instrumentation.(*Manager).load\n\t/home/matheus/tmp/opentelemetry-go-instrumentation/internal/pkg/instrumentation/manager.go:165\ngo.opentelemetry.io/auto/internal/pkg/instrumentation.(*Manager).Run\n\t/home/matheus/tmp/opentelemetry-go-instrumentation/internal/pkg/instrumentation/manager.go:120\ngo.opentelemetry.io/auto.(*Instrumentation).Run\n\t/home/matheus/tmp/opentelemetry-go-instrumentation/instrumentation.go:152\nmain.main\n\t/home/matheus/tmp/opentelemetry-go-instrumentation/cli/main.go:108\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:267"}
{"level":"info","ts":1702752038.8225884,"logger":"Instrumentation.Manager","caller":"instrumentation/manager.go:190","msg":"Cleaning bpffs"}
{"level":"error","ts":1702752038.8228626,"logger":"go.opentelemetry.io/auto","caller":"cli/main.go:109","msg":"instrumentation crashed","error":"field UprobeTransportRoundTrip: program uprobe_Transport_roundTrip: load program: invalid argument: unknown func bpf_probe_write_user#36 (617 line(s) omitted)","stacktrace":"main.main\n\t/home/matheus/tmp/opentelemetry-go-instrumentation/cli/main.go:109\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:267"}
```

### Expected behavior

`opentelemetry-go-instrumentation` initializes successfully.

### Additional context

Sample program:
```go
package main

import (
	"fmt"
	"net/http"
	"time"
)

func greet(w http.ResponseWriter, r *http.Request) {
	resp, err := http.Get("https://www.google.com")
	if err != nil {
		w.WriteHeader(http.StatusInternalServerError)
	}
	fmt.Fprintf(w, "status code %d at %s", resp.StatusCode, time.Now())
}

func main() {
	http.HandleFunc("/", greet)
	http.ListenAndServe(":8080", nil)
}
```

**Comment by RonFed** [comment] 2023-12-17 09:19
This is a duplicate of #290

**Comment by matheusjunior** [comment] 2023-12-17 22:51
I see; I searched for `UprobeTransportRoundTrip` in the open issues but should have searched for `bpf_probe_write_user`. You may close this ticket. Thank you.

**Comment by MrAlias** [comment] 2024-11-21 21:41
Unifying with #290. Closing.

**Closed by MrAlias** 2024-11-21 21:41 UTC
Labels: bug
